// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD16KZJ4oGMxllyYjN6cPMKFYGqBWOiqu8',
    appId: '1:1011179499871:web:6acea4be51f17f66d906ea',
    messagingSenderId: '1011179499871',
    projectId: 'thecaiosenorita8967',
    authDomain: 'thecaiosenorita8967.firebaseapp.com',
    databaseURL: 'https://thecaiosenorita8967-default-rtdb.firebaseio.com',
    storageBucket: 'thecaiosenorita8967.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16KZJ4oGMxllyYjN6cPMKFYGqBWOiqu8',
    appId: '1:1011179499871:android:6acea4be51f17f66d906ea',
    messagingSenderId: '1011179499871',
    projectId: 'thecaiosenorita8967',
    authDomain: 'thecaiosenorita8967.firebaseapp.com',
    databaseURL: 'https://thecaiosenorita8967-default-rtdb.firebaseio.com',
    storageBucket: 'thecaiosenorita8967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD16KZJ4oGMxllyYjN6cPMKFYGqBWOiqu8',
    appId: '1:1011179499871:ios:6acea4be51f17f66d906ea',
    messagingSenderId: '1011179499871',
    projectId: 'thecaiosenorita8967',
    authDomain: 'thecaiosenorita8967.firebaseapp.com',
    databaseURL: 'https://thecaiosenorita8967-default-rtdb.firebaseio.com',
    storageBucket: 'thecaiosenorita8967.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD16KZJ4oGMxllyYjN6cPMKFYGqBWOiqu8',
    appId: '1:1011179499871:ios:6acea4be51f17f66d906ea',
    messagingSenderId: '1011179499871',
    projectId: 'thecaiosenorita8967',
    authDomain: 'thecaiosenorita8967.firebaseapp.com',
    databaseURL: 'https://thecaiosenorita8967-default-rtdb.firebaseio.com',
    storageBucket: 'thecaiosenorita8967.firebasestorage.app',
  );
}